/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Nikola
 */
public class FrmRaspored extends javax.swing.JDialog {

    /**
     * Creates new form FrmRaspored
     */
    public FrmRaspored(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRaspored = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRaspored = new javax.swing.JTable();
        btnNadji = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nadji raspored:");

        tblRaspored.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRaspored);

        btnNadji.setText("Nadji");

        btnDodaj.setText("Dodaj");

        btnDetalji.setText("Detalji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(txtRaspored, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNadji)
                    .addComponent(btnDodaj)
                    .addComponent(btnDetalji))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRaspored, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNadji))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addGap(18, 18, 18)
                        .addComponent(btnDetalji)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnNadji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRaspored;
    private javax.swing.JTextField txtRaspored;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnDetalji() {
        return btnDetalji;
    }

    public void setBtnDetalji(JButton btnDetalji) {
        this.btnDetalji = btnDetalji;
    }

    public JButton getBtnDodaj() {
        return btnDodaj;
    }

    public void setBtnDodaj(JButton btnDodaj) {
        this.btnDodaj = btnDodaj;
    }

    public JButton getBtnNadji() {
        return btnNadji;
    }

    public void setBtnNadji(JButton btnNadji) {
        this.btnNadji = btnNadji;
    }

    public JTable getTblRaspored() {
        return tblRaspored;
    }

    public void setTblRaspored(JTable tblRaspored) {
        this.tblRaspored = tblRaspored;
    }

    public JTextField getTxtRaspored() {
        return txtRaspored;
    }

    public void setTxtRaspored(JTextField txtRaspored) {
        this.txtRaspored = txtRaspored;
    }

    public void dodajBtnNadjiListener(ActionListener actionListener) {
        btnNadji.addActionListener(actionListener);
    }

    public void dodajBtnDetaljiListener(ActionListener actionListener) {
        btnDetalji.addActionListener(actionListener);
    }

    public void dodajBtnDodajListener(ActionListener actionListener) {
        btnDodaj.addActionListener(actionListener);
    }

}
